---
- name: LDAP sync CronJob
  block:
    - name: Create ConfigMap for LDAP sync
      k8s:
        state: present
        kind: ConfigMap
        api_version: v1
        name: ldap-sync
        namespace: openshift-config
        merge_type: 
          - strategic-merge
          - merge     
        definition:
          data:
            ldap-sync.sh: >-
              #!/bin/sh
          
              oc adm groups sync --sync-config=/ldap-sync/ldap-sync.yaml
              --whitelist=/ldap-sync/whitelist.yaml --confirm; echo "Above AD Groups were
              synced with OCP"
            ldap-sync.yaml: |
              kind: LDAPSyncConfig
              apiVersion: v1
              url: "{{ ad_sync_server_url }}"
              insecure: true
              bindDN: "{{ ad_sync_service_account }}"
              bindPassword: "{{ ad_sync_password }}"
              augmentedActiveDirectory:
                  groupsQuery:
                      baseDN: "{{ ad_sync_group_base_dn }}"
                      scope: "{{ ad_sync_group_scope }}"
                      derefAliases: never
                      pageSize: 0
                  groupUIDAttribute: "{{ ad_sync_group_groupUIDAttribute }}"
                  groupNameAttributes: [ "{{ ad_sync_group_groupNameAttributes }}" ]
                  usersQuery:
                      baseDN: "{{ ad_sync_user_base_dn }}"
                      scope: "{{ ad_sync_user_scope }}"
                      filter: "{{ ad_sync_user_filter }}"
                      derefAliases: never
                      pageSize: 0
                  userNameAttributes: [ "{{ ad_sync_user_userNameAttributes }}" ]
                  groupMembershipAttributes: [ "{{ ad_sync_user_groupMembershipAttributes }}" ]
            whitelist.yaml: |
              cn="{{ ad_sync_group_1 }}","{{ ad_sync_group_base_dn }}"
              cn="{{ ad_sync_group_2 }}","{{ ad_sync_group_base_dn }}"
              cn="{{ ad_sync_group_3 }}","{{ ad_sync_group_base_dn }}"


    - name: Create CronJob for LDAP sync
      k8s:
        state: present
        kind: CronJob
        api_version: batch/v1beta1
        name: ldap-sync
        namespace: openshift-config
        merge_type: 
          - strategic-merge
          - merge     
        definition:
          metadata:
            labels:
              run: ldap-sync
          spec:
            schedule: '{{ ldap_cron_schedule }}'
            concurrencyPolicy: Replace
            suspend: false
            jobTemplate:
              metadata:
                creationTimestamp: null
              spec:
                template:
                  metadata:
                    creationTimestamp: null
                    labels:
                      run: ldap-sync
                  spec:
                    restartPolicy: OnFailure
                    serviceAccountName: approver
                    containers:
                      - name: ldap-sync
                        image: registry.redhat.io/openshift4/ose-cli
                        command:
                          - /bin/sh
                          - '-c'
                          - /ldap-sync/ldap-sync.sh
                        resources: {}
                        volumeMounts:
                          - name: ldap-sync
                            mountPath: /ldap-sync
                        terminationMessagePath: /dev/termination-log
                        terminationMessagePolicy: File
                        imagePullPolicy: Always
                    serviceAccount: approver
                    volumes:
                      - name: ldap-sync
                        configMap:
                          name: ldap-sync
                          defaultMode: 347
