---
- name: Authentication via HTPasswd
  block:
    - name: "Import the htpasswd task file."
      import_tasks: htpasswd.yml
  when: auth == "HTPasswd"

- name: "Authentication via AD"
  block:
    - name: "Import the htpasswd task file."
      import_tasks: ad_integration.yml

    - name: "Import the htpasswd task file."
      import_tasks: ad_sync.yml
      when: ad_sync

  when: auth == "AD"
