---
# tasks file for monitoring

- name: Create / set Namespace for cluster monitoring
  k8s:
    state: present
    api_version: v1
    kind: Namespace
    name: "{{ monitoring_namespace }}"

- name: Create cluster monitoring ConfigMap
  k8s:
    state: present
    namespace: "{{ monitoring_namespace }}"
    definition:
      api_version: v1
      kind: ConfigMap
      metadata:
        name: "{{ monitoring-configmap-name }}"
      data:
        config.yml: |
          *insert configmap here*

   
